twist_pid_controller:
  ros__parameters:
    kp_linear: 1.0
    ki_linear: 0.0
    kd_linear: 0.0

    kp_angular: 1.0
    ki_angular: 0.0
    kd_angular: 0.0

    max_integral_linear: 1.0
    max_integral_angular: 1.0

    control_frequency: 50.0

    debug: true  # Enable debug mode
    debug_topic: "pid_debug"  # Topic name for debug messages
